import { PriceBracketDto } from './priceBracket.dto';
import { TagsDto } from '../../products/dto/tags.dto';
import { Grade, InventoryGrade } from '../../products/dto/consumerContents.dto';
import { GstInfoDto } from './gstInfo.dto';

export class InventoryProductCategoryDto {
  inventory_id: string;
  inventory_quantity: number;
  inventory_market_price: number;
  inventory_sale_price: number;
  inventory_max_price: number;
  inventory_sku_code: string;
  inventory_price_brackets: PriceBracketDto[];
  inventory_store_id: string;
  inventory_created_at: Date;
  inventory_updated_at: Date;
  inventory_updated_by: string;
  inventory_availability: number;
  inventory_cutoff_time: string;
  inventory_is_ozone_washed_item: boolean;
  inventory_ozone_washing_charges: number;
  inventory_grades: InventoryGrade[];
  product_id: number;
  product_sku_code: string;
  product_hsn: string;
  product_category_id: number;
  product_name: string;
  product_packet_description: string;
  product_image_url: string;
  product_tags: TagsDto[];
  product_serves1: number;
  product_is_active: boolean;
  product_unit_of_measurement: string;
  product_market_price: number;
  product_sale_price: number;
  product_per_pcs_suffix: string;
  product_per_pcs_weight: number;
  product_display_name: string;
  product_min_quantity: number;
  product_max_quantity: number;
  product_buffer_quantity: number;
  product_is_coins_redeemable: number;
  product_consumer_contents: object;
  product_created_at: Date;
  product_updated_at: Date;
  product_updated_by: string;
  product_gst: GstInfoDto;
  category_id: number;
  category_name: string;
  category_image_url: string;
  category_created_at: Date;
  category_is_active: boolean;
  category_updated_at: Date;
  category_updated_by: string;
  is_complimentary: boolean;
  isPreBook: boolean;
  preBookDate: string;
}
